name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build .app
        run: |
          # Add commands to turn your Python script into a .app


      - name: Debug
        run: |
          ls -l
          echo "Current directory contents:"
          ls -la
          echo "Current version: $current_version"
        working-directory: ${{ github.workspace }}




      - name: Update version number
        run: |
          awk -F= '/VERSION/ {printf "VERSION=%.1f\n", $2 + 0.1; next} {print}' version.txt > version.tmp && mv version.tmp version.txt

        

      - name: Commit changes
        run: |
          git config --global user.name 'Ryan Krohne'
          git config --global user.email 'rkrohnesoccer@gmail.com'
          git add version.txt
          git commit -m "Update version number" --author="Ryan Krohne <rkrohnesoccer@gmail.com>"
          git push
