name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build .app
        run: |
          # Add commands to turn your Python script into a .app


      - name: Debug
        run: |
          ls -l
          echo "Current directory contents:"
          ls -la
          echo "Current version: $current_version"
        working-directory: ${{ github.workspace }}




      - name: Update version number
        run: |
          sed -i 's/VERSION=1.1/VERSION=0.0/' version.txt
        

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Update version number"
          git push
